#!/bin/bash

# Arg 1 is link to make, arg 2 is where to point to
syncFile() {
	if [ -f $1 ]; then
		if [[ -L $1 ]]; then
			printf "File $(tput setaf 3)$1$(tput sgr0) is already a link\n"
			return  
		fi
		
		printf "File $(tput setaf 3)$1$(tput sgr0) already exists.\n"
		printf "Do you want to delete it and create the symlink $1 -> $2? [Y/N]"
		read resp

		if [ "$resp" = 'y' -o "$resp" = 'Y' ] ; then
			printf "\tDeleting $(tput setaf 3)$1$(tput sgr0)\n"
			rm $1
			printf "\tCreating symlink $1 -> $2\n\n"
			ln -s $2 $1
		else
			printf "\tSkipping\n\n"
			return
		fi
	fi

}

syncFile ~/.vimrc ~/dotFiles/terminal/.vimrc
syncFile ~/.bashrc ~/dotFiles/terminal/.bashrc
syncFile ~/.tmux.conf ~/dotFiles/terminal/.tmux.conf
syncFile ~/.zshrc ~/dotFiles/terminal/.zshrc
